package com.udea.parcial.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.*;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class DoctorDTO {
    @Schema(description = "Autogenerated by the DB")
    private long doctorId;

    @Schema(description = "Full name of the doctor")
    @NotBlank(message = "Name is required")
    @Size(min = 1, max = 100)
    private String name;

    @Schema(description = "Identification number of the doctor")
    @NotBlank(message = "Identification Number is required")
    @Pattern(regexp = "^[0-9]{10}", message = "Identification Number must be 10 digits")
    @Size(min = 10, max = 10)
    private String identificationNumber;

    @Schema(description = "Specialty of the doctor")
    @NotBlank(message = "Specialty is required")
    @Size(min = 1, max = 100)
    private String specialty;

    @Schema(description = "Phone number of the doctor")
    @NotBlank(message = "Phone number is required")
    @Pattern(regexp = "^[0-9]{10}", message = "Phone number must be 10 digits")
    @Size(min = 10, max = 10)
    private String phone;

    @Schema(description = "Email of the doctor")
    @NotBlank(message = "Email is required")
    @Email(message = "Email should be valid")
    @Size(min = 5, max = 100)
    private String email;
}