package com.udea.parcial.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.*;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class MedicalHistoryDTO {
    @Schema(description = "Autogenerated by the DB")
    private long medicalHistoryId;

    @Schema(description = "Identification Number of the associated patient")
    @NotBlank(message = "Identification Number of the patient is required")
    @Pattern(regexp = "^[0-9]{10}", message = "Identification Number must be 10 digits")
    @Size(min = 10, max = 10)
    private String identificationNumberPatient;

    @Schema(description = "Identification Number of the doctor who recorded the history")
    @NotBlank(message = "Identification Number of the doctor is required")
    @Pattern(regexp = "^[0-9]{10}", message = "Identification Number must be 10 digits")
    @Size(min = 10, max = 10)
    private String identificationNumberDoctor;

    @Schema(description = "Date when the record was made")
    @NotBlank(message = "Date of Record is required")
    @Size(min = 9, max = 10)
    private String dateOfRecord;

    @Schema(description = "Diagnosis of the patient")
    @NotBlank(message = "Diagnosis is required")
    @Size(min = 1, max = 500)
    private String diagnosis;

    @Schema(description = "Recommended treatment for the patient")
    @NotBlank(message = "Treatment is required")
    @Size(min = 1, max = 500)
    private String treatment;

    @Schema(description = "Additional notes from the doctor")
    @Size(min = 1, max = 1000)
    private String additionalNotes;
}
