package com.udea.parcial.model;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.*;

import java.io.Serializable;
import java.time.LocalDate;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@ToString
@Schema(description =  "Details of the patient")
@Entity
public class Patient implements Serializable {
    @Schema(description = "Autogenerated by the DB")
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "patient_id")
    private long patientId;

    @Schema(description = "Full name of the patient")
    @Column(name = "name", nullable = false)
    private String name;

    @Schema(description = "indentification_number of the patient")
    @Column(name = "identification_number", nullable = false, unique = true)
    private String identification_number;

    @Schema(description = "Date of birth of the patient")
    @Temporal(TemporalType.DATE)
    @Column(name = "date_of_birth", nullable = false)
    private LocalDate dateOfBirth;

    @Schema(description = "Address of the patient")
    @Column(name = "address", nullable = false)
    private String address;

    @Schema(description = "Phone number of the patient")
    @Column(name = "phone", nullable = false)
    private String phone;

    @Schema(description = "Email of the patient")
    @Column(name = "email", nullable = false)
    private String email;
}